add missing constexpr in win32_9xa_dirent (#1080)
there is the traceback before this patch:
D:/projects/Phy-Engine/test/../include/fast_io/fast_io_hosted/filesystem/win32_9xa.h:273:19: error: destructor cannot be declared constexpr because data member 'entry' does not have a constexpr destructor
  273 |         inline constexpr ~basic_win32_9xa_recursive_directory_generator()
      |                          ^
D:/projects/Phy-Engine/test/../include/fast_io/fast_io_hosted/filesystem/win32_9xa.h:250:19: note: data member 'entry' declared here
  250 |         win32_9xa_dirent entry{};
      |                          ^